GET http://localhost:5118/todos

###

GET http://localhost:5118/tasks/1

###

POST http://localhost:5118/todos HTTP/1.1
content-type: application/json

{
"Id": 1,
"Name":"Rafaela",
"DueDate": "2025-05-23",
"IsCompleted": false
}

### 

DELETE http://localhost:5118/todos/1